#!/usr/bin/env python3
"""Generate code from the glossary (ADR-0012: the glossary is the master schema).

Reads the variable table in docs/glossary.md and writes
crates/econ-types/src/glossary.rs (a registry of canonical variable names).
`--check` fails if the generated file is out of date (CI).

Usage:
    python scripts/codegen_glossary.py          # regenerate
    python scripts/codegen_glossary.py --check  # verify (CI / just check)
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GLOSSARY = ROOT / "docs" / "glossary.md"
OUT = ROOT / "crates" / "econ-types" / "src" / "glossary.rs"


def rust_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def parse() -> list[dict]:
    rows = []
    in_table = False
    for line in GLOSSARY.read_text(encoding="utf-8").splitlines():
        if line.startswith("| Symbol | code_name"):
            in_table = True
            continue
        if in_table:
            if not line.startswith("|"):
                break
            if line.startswith("|---"):
                continue
            cells = [c.strip() for c in line.strip().strip("|").split("|")]
            if len(cells) < 6:
                continue
            _, code, meaning, unit, kind, owner = cells[:6]
            for name in re.findall(r"`([^`]+)`", code):
                rows.append({"code_name": name, "meaning": meaning, "unit": unit, "kind": kind, "owner": owner})
    return rows


def render(rows: list[dict]) -> str:
    out = [
        "//! GENERATED by scripts/codegen_glossary.py from docs/glossary.md — do not edit.",
        "//! The glossary is the single source of truth for variable names (ADR-0012).",
        "",
        "/// One canonical variable from the glossary.",
        "#[derive(Debug, Clone, Copy, PartialEq, Eq)]",
        "pub struct Variable {",
        "    /// Canonical code name (may include an index suffix like `[g]`).",
        "    pub code_name: &'static str,",
        "    /// Meaning.",
        "    pub meaning: &'static str,",
        "    /// Unit.",
        "    pub unit: &'static str,",
        "    /// state / flow / derived / lever / parameter / exogenous.",
        "    pub kind: &'static str,",
        "    /// Owning spec id.",
        "    pub owner: &'static str,",
        "}",
        "",
        "/// Every variable in the glossary, in table order.",
        "pub const VARIABLES: &[Variable] = &[",
    ]
    for r in rows:
        out.append(
            f"    Variable {{ code_name: {rust_str(r['code_name'])}, meaning: {rust_str(r['meaning'])}, "
            f"unit: {rust_str(r['unit'])}, kind: {rust_str(r['kind'])}, owner: {rust_str(r['owner'])} }},"
        )
    out += [
        "];",
        "",
        "/// Look up a variable by its canonical code name.",
        "#[must_use]",
        "pub fn lookup(code_name: &str) -> Option<&'static Variable> {",
        "    VARIABLES.iter().find(|v| v.code_name == code_name)",
        "}",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    rows = parse()
    names = [r["code_name"] for r in rows]
    dups = sorted({n for n in names if names.count(n) > 1})
    if dups:
        print("Duplicate code_names in glossary:", dups)
        return 1
    content = render(rows)
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print("crates/econ-types/src/glossary.rs is stale. Run: python scripts/codegen_glossary.py")
            return 1
        print(f"OK — glossary codegen up to date ({len(rows)} variables).")
        return 0
    OUT.write_text(content, encoding="utf-8")
    print(f"OK — wrote {OUT.relative_to(ROOT)} ({len(rows)} variables).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
