#!/usr/bin/env python3
"""Validate doc frontmatter and regenerate docs/INDEX.md.

Usage:
    python scripts/docs_index.py          # validate + write INDEX.md
    python scripts/docs_index.py --check  # validate + fail if INDEX.md is stale (CI)

No dependencies beyond the standard library.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "INDEX.md"
REQUIRED = ["id", "title", "status", "owner", "depends_on", "updated"]
STATUSES = {"stub", "researching", "draft", "review", "locked",  # specs / notes
            "proposed", "accepted", "superseded"}                # ADRs
SKIP_DIRS = {"templates"}


def parse_frontmatter(text):
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if not m:
        return None
    fm = {}
    for line in m.group(1).splitlines():
        line = line.split("#", 1)[0].rstrip()
        if not line or ":" not in line:
            continue
        key, val = line.split(":", 1)
        val = val.strip().strip('"')
        if val.startswith("[") and val.endswith("]"):
            val = [v.strip() for v in val[1:-1].split(",") if v.strip()]
        fm[key.strip()] = val
    return fm


def collect():
    docs, errors = [], []
    for path in sorted(DOCS.rglob("*.md")):
        rel = path.relative_to(DOCS)
        if path == INDEX or rel.parts[0] in SKIP_DIRS:
            continue
        fm = parse_frontmatter(path.read_text(encoding="utf-8"))
        if fm is None:
            errors.append(f"{rel}: missing frontmatter")
            continue
        for key in REQUIRED:
            if key not in fm:
                errors.append(f"{rel}: missing '{key}'")
        if fm.get("status") not in STATUSES:
            errors.append(f"{rel}: invalid status '{fm.get('status')}'")
        fm["_path"] = rel.as_posix()
        docs.append(fm)

    ids = {}
    for d in docs:
        if d.get("id") in ids:
            errors.append(f"{d['_path']}: duplicate id '{d['id']}' (also {ids[d['id']]})")
        ids[d.get("id")] = d["_path"]
    for d in docs:
        for field in ("depends_on", "research"):
            for dep in d.get(field, []) or []:
                if dep not in ids:
                    errors.append(f"{d['_path']}: {field} -> unknown id '{dep}'")
    return docs, errors


def render(docs):
    out = ["# Docs Index", "",
           "_Auto-generated by `scripts/docs_index.py` — do not edit by hand._", ""]
    counts = {}
    for d in docs:
        counts[d["status"]] = counts.get(d["status"], 0) + 1
    out.append("**Status:** " + " · ".join(f"{k}: {v}" for k, v in sorted(counts.items())))
    out.append("")
    section = None
    for d in sorted(docs, key=lambda d: d["_path"]):
        top = d["_path"].split("/")[0] if "/" in d["_path"] else "(root)"
        if top != section:
            section = top
            out += ["", f"## {section}", "", "| Doc | id | Status | Depends on | Updated |", "|---|---|---|---|---|"]
        deps = ", ".join(d.get("depends_on") or []) or "—"
        out.append(f"| [{d['title']}]({d['_path']}) | `{d['id']}` | {d['status']} | {deps} | {d['updated']} |")
    return "\n".join(out) + "\n"


def main():
    docs, errors = collect()
    if errors:
        print("Frontmatter errors:")
        for e in errors:
            print("  -", e)
        sys.exit(1)
    content = render(docs)
    if "--check" in sys.argv:
        if not INDEX.exists() or INDEX.read_text(encoding="utf-8") != content:
            print("docs/INDEX.md is stale. Run: python scripts/docs_index.py")
            sys.exit(1)
        print(f"OK — {len(docs)} docs, index up to date.")
        return
    INDEX.write_text(content, encoding="utf-8")
    print(f"OK — {len(docs)} docs indexed -> docs/INDEX.md")


if __name__ == "__main__":
    main()
