//! Core value types shared by every econ-sim crate.
//!
//! * [`Bani`]: money as an integer number of bani (1 RON = 100 bani), with
//!   arithmetic that panics on overflow in every build (ADR-0007).
//! * ID newtypes.
//! * [`Day`] (one simulation tick), [`Date`] and [`Calendar`] (ADR-0017).
//!
//! This crate has no dependencies so that every other crate can use it.

#![warn(clippy::arithmetic_side_effects, clippy::cast_possible_truncation)]

mod bani;
#[rustfmt::skip] // generated by scripts/codegen_glossary.py
pub mod glossary;
mod ids;
mod time;

pub use bani::{Bani, split_largest_remainder};
pub use ids::{CountyId, FirmId, HouseholdId, IndustryId, PersonId};
pub use time::{Calendar, Date, Day, Month};
